stages:
    - deploy

push_heroku:
    stage: deploy
    script:
        - echo "Now, start deploying project to Heroku.->"
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROJECT_NAME --api-key=$HEROKU_API_KEY
    only:
        - heroku
