stages:
    - safety
    - deploy

default:
    before_script:
        - apt-get update -qy

safety_check:
    # https://pyup.io/safety/
    stage: safety
    script:
        - apt-get install -y python3-dev python3-pip
        - pip3 install pipenv
        - pipenv install
        - pipenv run pip3 install safety
        - pipenv run safety check
    only:
        - merge_requests
        - schedules

push_heroku:
    stage: deploy
    script:
        - echo "Now, start deploying project to Heroku.->"
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROJECT_NAME --api-key=$HEROKU_API_KEY
    only:
        - heroku
